name: Release NPM package

on:
  push:
    tags: ['v2.*']

jobs:
  build:
    runs-on: ubuntu-latest
    name: Node build
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn

      - run: yarn install --frozen-lockfile --non-interactive

      - run: yarn run build

  release:
    needs: [build]
    runs-on: ubuntu-latest
    name: Release
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Set tag
        id: tagName
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn

      - run: yarn install --frozen-lockfile --non-interactive

      - uses: JS-DevTools/npm-publish@v1
        with:
          tag: v1
          token: ${{ secrets.NPM_TOKEN }}
